name: Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - run: wget --debug --verbose https://invisible-mirror.net/archives/ncurses/6.1/ncurses-6.1-20190609-patch.sh.bz2
